# time	MEK_pRDS_WT scaled_pSOS1    scaled_pEGFR    scaled_pERK 
0       nan         0               1.5             0.9        
300     nan         4.2             10              9.9                 
600     nan         9.5             9.6             9.0                         
900     nan         10              6.1             7.9                       
1800    nan         9.5             2.9             5.0                    
3600    nan         6.9             1.9             3.5      
